-- Schema core per Flow Starter (Supabase/Postgres)

-- Tabella profili utente (se non esiste)
create table if not exists public.profiles (
  id uuid primary key,
  email text,
  credits numeric default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Tabella ledger transazioni crediti
create table if not exists public.credit_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  amount numeric not null,
  reason text,
  created_at timestamp with time zone default now()
);

-- Indice per performance
create index if not exists idx_credit_tx_user_id on public.credit_transactions(user_id);

-- Funzione atomica per addebitare crediti
create or replace function public.debit_user_credits(
  p_user_id uuid,
  p_amount numeric,
  p_reason text default 'debit'
) returns json as $$
declare
  v_before numeric;
  v_after numeric;
begin
  if p_amount is null or p_amount <= 0 then
    return json_build_object('success', false, 'error', 'invalid_amount');
  end if;

  select credits into v_before from public.profiles where id = p_user_id for update;
  if v_before is null then
    return json_build_object('success', false, 'error', 'user_not_found');
  end if;
  if v_before < p_amount then
    return json_build_object('success', false, 'error', 'insufficient_credits', 'available', v_before, 'required', p_amount);
  end if;

  v_after := v_before - p_amount;
  update public.profiles set credits = v_after, updated_at = now() where id = p_user_id;

  insert into public.credit_transactions(user_id, amount, reason)
  values (p_user_id, -p_amount, p_reason);

  return json_build_object('success', true, 'credits_before', v_before, 'credits_after', v_after);
end;
$$ language plpgsql security definer;

-- Policy raccomandate (RLS da adattare al contesto)
alter table public.profiles enable row level security;
alter table public.credit_transactions enable row level security;

-- Esempio policy: accesso in lettura al proprio record (da adattare a auth.uid())
do $$ begin
  begin
    create policy profiles_select_self on public.profiles
      for select using (id = auth.uid());
  exception when duplicate_object then null; end;
  begin
    create policy credit_tx_select_self on public.credit_transactions
      for select using (user_id = auth.uid());
  exception when duplicate_object then null; end;
end $$;


